name: dotnet package

on:
  push:
    paths:
      - 'src/Api/**'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['7.0' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        working-directory: ./src/Api
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: ./src/Api
      - name: Test
        run: dotnet test --no-restore --verbosity normal
        working-directory: ./src/Api
      - name: Add Microsoft.NET.Build.Containers package
        working-directory: ./src/Api
        run: dotnet add package Microsoft.NET.Build.Containers
      - name: dotnet publish
        working-directory: ./src/Api
        run: dotnet publish -p PublishProfile=DefaultContainer
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_URI }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: docker tag for ACR, latest
        run: docker tag nebula-api:latest ${{ secrets.ACR_URI }}/nebula-api:latest
      - name: docker push to ACR, latest
        run: docker push ${{ secrets.ACR_URI }}/nebula-api:latest
      - name: docker tag for ACR, github.sha
        run: docker tag nebula-api:latest ${{ secrets.ACR_URI }}/nebula-api:${{ github.sha }}
      - name: docker push to ACR, github.sha
        run: docker push ${{ secrets.ACR_URI }}/nebula-api:${{ github.sha }}
      